
/**
* @author CallmeSun
* @warn Vui lòng không sửa credits cảm ơn !
*/
module.exports.config = {
  name: "chill",
  version: "1.0.0",
  hasPermssion: 0,
  credits: "CallmeSun",
  description: "video Nhạc",
  commandCategory: "Quản Lý Box",
  usages: "girlnude",
  cooldowns: 5,
  dependencies: {
    "request":"",
    "fs-extra":"",
    "axios":""
  }
};

module.exports.run = async({api,event,args,client,Users,Threads,__GLOBAL,Currencies}) => {
const axios = global.nodemodule["axios"];
const request = global.nodemodule["request"];
const fs = global.nodemodule["fs-extra"];
  var link = [
    "https://i.imgur.com/yPJPv4q.mp4", 
    "https://i.imgur.com/WjVfowo.mp4",
    "https://i.imgur.com/zrXPSrr.mp4", 
    "https://i.imgur.com/a7TEDRg.mp4",  
    "https://i.imgur.com/GoWRsbs.mp4",
    "https://i.imgur.com/rXpxjRa.mp4",
    "https://i.imgur.com/4Y7gK9i.mp4",
    "https://i.imgur.com/4MzJAbm.mp4",
    "https://i.imgur.com/Ff0C8tf.mp4",
    "https://i.imgur.com/EXAf0wt.mp4", 
    "https://i.imgur.com/H3t7YUV.mp4",
    "https://i.imgur.com/sPi2RHJ.mp4",
    "https://i.imgur.com/Yd3BOZr.mp4",
    "https://i.imgur.com/k7dWZLk.mp4",
    "https://i.imgur.com/3UEW4Eq.mp4",
    "https://i.imgur.com/ava5Utg.mp4",
    "https://i.imgur.com/knkStTE.mp4",
    "https://i.imgur.com/kv6B97I.mp4",
    "https://i.imgur.com/LlIji4C.mp4",
    "https://i.imgur.com/HQaDwg0.mp4",
    "https://i.imgur.com/5vzomnU.mp4", 
    "https://i.imgur.com/5BGsgYw.mp4",
    "https://i.imgur.com/5cl8mYW.mp4", 
    "https://i.imgur.com/pkSzgHG.mp4", 
    "https://i.imgur.com/8fwXHg5.mp4", 
    "https://i.imgur.com/dzuBaia.mp4",
    "https://i.imgur.com/CEALr4l.mp4", 
    "https://i.imgur.com/7Dvm4g7.mp4",
    "https://i.imgur.com/hhV9keY.mp4",
    "https://i.imgur.com/4UEWszw.mp4", 
    "https://i.imgur.com/UjPz94q.mp4", 
    "https://i.imgur.com/ERyqDST.mp4", 
    "https://i.imgur.com/Qy7kmIU.mp4", 
    "https://i.imgur.com/5vsLdkw.mp4",
    "https://i.imgur.com/tUDUEtc.mp4", 
    "https://i.imgur.com/2cIbhP3.mp4",
    "https://i.imgur.com/swqikQN.mp4", 
    "https://i.imgur.com/XUtldkn.mp4", 
    "https://i.imgur.com/dmz3csF.mp4", 
    "https://i.imgur.com/LODPRSg.mp4",
    "https://i.imgur.com/z88hoDp.mp4",
    "https://i.imgur.com/br7xCek.mp4",
    "https://i.imgur.com/zg84Cyp.mp4", 
    "https://i.imgur.com/0z8ppON.mp4", 
    "https://i.imgur.com/sP21V31.mp4", 
    "https://i.imgur.com/szI1tlX.mp4",
    "https://i.imgur.com/hihJmJC.mp4",
    "https://i.imgur.com/5orFI43.mp4", 
    "https://i.imgur.com/BbHnJML.mp4",
    "https://i.imgur.com/oZUcIih.mp4",
 "https://i.imgur.com/nf946UF.mp4",
 "https://i.imgur.com/TOTHWmj.mp4",
 "https://i.imgur.com/wGizhkB.mp4",
 "https://i.imgur.com/NdBA0xa.mp4",
 "https://i.imgur.com/7a2qIHP.mp4",
 "https://i.imgur.com/ykRapjY.mp4",
 "https://i.imgur.com/k9U4ga7.mp4",
 "https://i.imgur.com/eTGecWK.mp4",
 "https://i.imgur.com/GqEMZYX.mp4",
 "https://i.imgur.com/wGUeudA.mp4",
 "https://i.imgur.com/eH0gEZ8.mp4",
 "https://i.imgur.com/UjH3XKp.mp4",
 "https://i.imgur.com/ohulyJh.mp4",
 "https://i.imgur.com/e9edVJE.mp4",
 "https://i.imgur.com/ccyLSaZ.mp4",
 "https://i.imgur.com/ykK3FOd.mp4",
 "https://i.imgur.com/apjK7Bo.mp4",
 "https://i.imgur.com/DrLBsx2.mp4",
 "https://i.imgur.com/TuSoxC3.mp4",
 "https://i.imgur.com/mLq9Ilr.mp4",
 "https://i.imgur.com/A3gUT0r.mp4",
 "https://i.imgur.com/SJa8glr.mp4",
 "https://i.imgur.com/jRDwQd0.mp4",
 "https://i.imgur.com/wVCJiFC.mp4",
 "https://i.imgur.com/vxxglXy.mp4",
 "https://i.imgur.com/7mq6N0P.mp4",
 "https://i.imgur.com/xTRirSq.mp4",
 "https://i.imgur.com/KDgmB0A.mp4",
 "https://i.imgur.com/4YHjTjk.mp4",
 "https://i.imgur.com/IpAhAfs.mp4",
"https://i.imgur.com/0MIxBjr.mp4", 
"https://i.imgur.com/4xrJwmv.mp4", 
"https://i.imgur.com/4eWUjOh.mp4", 
"https://i.imgur.com/oZBwSi3.mp4", 
"https://i.imgur.com/OtdEtdj.mp4", 
"https://i.imgur.com/oYglUJz.mp4", 
"https://i.imgur.com/47bIbTP.mp4", 
"https://i.imgur.com/nwScB0k.mp4", 
"https://i.imgur.com/7j9uCCr.mp4", 
"https://i.imgur.com/mRygKIj.mp4", 
"https://i.imgur.com/jJSDKzL.mp4", 
"https://i.imgur.com/uIqDjXP.mp4", 
"https://i.imgur.com/IiKHRSE.mp4", 
"https://i.imgur.com/tcYNXoX.mp4", 
"https://i.imgur.com/sahL46m.mp4", 
"https://i.imgur.com/f6tmzWs.mp4", 
"https://i.imgur.com/CspU4Bd.mp4", 
"https://i.imgur.com/zOSwxlr.mp4", 
"https://i.imgur.com/IE2nKre.mp4", 
"https://i.imgur.com/GyZJlny.mp4", 
"https://i.imgur.com/zNecEcq.mp4", 
"https://i.imgur.com/uiwBgvx.mp4", 
"https://i.imgur.com/EG9lwvx.mp4", 
"https://i.imgur.com/lfvc5hC.mp4", 
"https://i.imgur.com/YlxxONH.mp4", 
"https://i.imgur.com/ULhB5QP.mp4", 
"https://i.imgur.com/KhadKy3.mp4", 
"https://i.imgur.com/0lf9kjx.mp4", 
"https://i.imgur.com/B6UMmPf.mp4", 
"https://i.imgur.com/2p9SeIv.mp4", 
"https://i.imgur.com/ZBK3z7j.mp4", 
"https://i.imgur.com/PFQSaHF.mp4", 
"https://i.imgur.com/33SQkCa.mp4", 
"https://i.imgur.com/yywc01G.mp4", 
"https://i.imgur.com/OJQoVaD.mp4", 
"https://i.imgur.com/UxIYb1O.mp4", 
"https://i.imgur.com/PQ07hEa.mp4", 
"https://i.imgur.com/ayj329b.mp4", 
"https://i.imgur.com/NmxZ3jo.mp4", 
"https://i.imgur.com/oNVekiM.mp4", 
"https://i.imgur.com/QjyU33W.mp4", 
"https://i.imgur.com/QQKjmip.mp4",
   "https://i.imgur.com/pLHFKmD.mp4",
 "https://i.imgur.com/nf946UF.mp4",
 "https://i.imgur.com/TOTHWmj.mp4",
 "https://i.imgur.com/wGizhkB.mp4",
 "https://i.imgur.com/NdBA0xa.mp4",
 "https://i.imgur.com/7a2qIHP.mp4",
 "https://i.imgur.com/ykRapjY.mp4",
 "https://i.imgur.com/k9U4ga7.mp4",
 "https://i.imgur.com/eTGecWK.mp4",
 "https://i.imgur.com/GqEMZYX.mp4",
 "https://i.imgur.com/wGUeudA.mp4",
 "https://i.imgur.com/eH0gEZ8.mp4",
 "https://i.imgur.com/UjH3XKp.mp4",
 "https://i.imgur.com/ohulyJh.mp4",
 "https://i.imgur.com/e9edVJE.mp4",
 "https://i.imgur.com/ccyLSaZ.mp4",
 "https://i.imgur.com/ykK3FOd.mp4",
 "https://i.imgur.com/apjK7Bo.mp4",
 "https://i.imgur.com/DrLBsx2.mp4",
 "https://i.imgur.com/TuSoxC3.mp4",
 "https://i.imgur.com/mLq9Ilr.mp4",
 "https://i.imgur.com/A3gUT0r.mp4",
 "https://i.imgur.com/SJa8glr.mp4",
 "https://i.imgur.com/jRDwQd0.mp4",
 "https://i.imgur.com/wVCJiFC.mp4",
 "https://i.imgur.com/vxxglXy.mp4",
 "https://i.imgur.com/7mq6N0P.mp4",
 "https://i.imgur.com/xTRirSq.mp4",
 "https://i.imgur.com/KDgmB0A.mp4",
 "https://i.imgur.com/4YHjTjk.mp4",
 "https://i.imgur.com/IpAhAfs.mp4",
"https://i.imgur.com/TRl17f7.mp4",
"https://i.imgur.com/yp9z5QN.mp4",
"https://i.imgur.com/qeIxxvn.mp4",
"https://i.imgur.com/LhINDGL.mp4",
"https://i.imgur.com/ygEYdzr.mp4",
"https://i.imgur.com/9thHnST.mp4",
"https://i.imgur.com/AMi9NiT.mp4",
"https://i.imgur.com/l8UisUZ.mp4",
"https://i.imgur.com/BZXJerW.mp4",
"https://i.imgur.com/xJpuVLs.mp4",
"https://i.imgur.com/MOQDCjg.mp4",
"https://i.imgur.com/kz7S5JO.mp4",
"https://i.imgur.com/K4pnAw0.mp4",
"https://i.imgur.com/WrPhJrH.mp4",
"https://i.imgur.com/fsol3MG.mp4",
"https://i.imgur.com/XT0d0a2.mp4",
"https://i.imgur.com/voxsCFv.mp4",
"https://i.imgur.com/QzyFnVK.mp4",
"https://i.imgur.com/BlI7Jbh.mp4",
"https://i.imgur.com/mK44Aod.mp4",
"https://i.imgur.com/UM95eCs.mp4",
"https://i.imgur.com/jDOLZYQ.mp4",
"https://i.imgur.com/xDfgeeD.mp4",
"https://i.imgur.com/iTUuWjl.mp4",
"https://i.imgur.com/WpnFSm5.mp4",
"https://i.imgur.com/nTw4lOF.mp4",
"https://i.imgur.com/5lrWddV.mp4",
"https://i.imgur.com/QRd4BCs.mp4",
"https://i.imgur.com/26ckWFR.mp4",
"https://i.imgur.com/Lzfz1kO.mp4",
"https://i.imgur.com/xVGLkGv.mp4",
"https://i.imgur.com/dXDJzCy.mp4",
"https://i.imgur.com/PPUGhmB.mp4",
"https://i.imgur.com/aZKx6VU.mp4",
"https://i.imgur.com/jG6uBjO.mp4",
"https://i.imgur.com/urLh5YY.mp4",
  ];
  var max = Math.floor(Math.random() * 6);  
  var min = Math.floor(Math.random() * 2);
  var data = await Currencies.getData(event.senderID);
  var exp =  data.exp;
  var money = data.money
      if(money < 0) api.sendMessage("Bạn cần 0 đô để xem video:V",event.threadID,event.messageID)
          else {
   Currencies.setData(event.senderID, options = {money: money - 0})
   var callback = () => api.sendMessage({body:`💿==== [ 𝐍𝐡𝐚̣𝐜 𝐂𝐡𝐢𝐥𝐥 ] ====💿\n\n━━━━━━━━━━━━━━━━\n「 𝐂𝐮̀𝐧𝐠 𝐜𝐡𝐢𝐥𝐥 𝐧𝐚̀𝐨 ${name} 」\n\n 𝐂𝐡𝐮́𝐜 ${name} 𝐍𝐠𝐡𝐞 𝐧𝐡𝐚̣𝐜 𝐯𝐮𝐢 𝐯𝐞̉ 𝐧𝐡𝐞́! `,attachment: fs.createReadStream(__dirname + "/cache/5.mp4")}, event.threadID, () => fs.unlinkSync(__dirname + "/cache/5.mp4"));
let name = await Users.getNameUser(event.senderID);
    let mentions = [];
    mentions.push({
      tag: name,
      id: event.senderID
    })            
      return request(encodeURI(link[Math.floor(Math.random() * link.length)])).pipe(fs.createWriteStream(__dirname+"/cache/5.mp4")).on("close",() => callback());
   }
};